services:
  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - sonnaz-site-prod
      - sonnaz-site-staging

  sonnaz-site-prod:
    image: ${PROD_SITE_IMAGE}
    restart: unless-stopped

  sonnaz-site-staging:
    image: ${STAGING_SITE_IMAGE}
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
